#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("R2B0app.Droid.Resource", IsApplication=true)]

namespace R2B0app.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Refractored.Xam.Forms.Vibrate.Droid.Resource.String.ApplicationName = global::R2B0app.Droid.Resource.String.ApplicationName;
			global::Refractored.Xam.Forms.Vibrate.Droid.Resource.String.Hello = global::R2B0app.Droid.Resource.String.Hello;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::R2B0app.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::R2B0app.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int iBuilder = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int iElectronic = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int iFont = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int iHardware = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int iMenu = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int iNetwork = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int iSoftware = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
